repos:
  - repo: local
    hooks:
      - id: ruff-check-and-fix
        name: Run Ruff check and fix
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: true
        args: []